version: '2'
services:
  server:
    container_name: server
    image: nodejs-webpack-es6-image
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - 3001:2000
  ui:
    container_name: ui
    build:
      context: ./ui/
    command: npm start
    volumes:
      - ./ui/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - 3000:3000